 1. 

In [ ]:
a1=tuple(["aman","222",777,400.4])
print(a1)

('aman', '222', 777, 400.4)


 2.

In [1]:
q={"rollno": "CB.EN.U4CSE20226","lname": "reddy","fname": "sujith","dob": "24-12-2001"}
print(q)

{'rollno': 'CB.EN.U4CSE20226', 'lname': 'reddy', 'fname': 'sujith', 'dob': '24-12-2001'}


 3.

In [ ]:
import numpy as np
np.random.seed(0)
arr=np.random.randint(0,50,size=(2,5))
print(arr)

[[44 47  0  3  3]
 [39  9 19 21 36]]


4. 

In [ ]:
print(round(random.uniform(0.1, 1.0), 10))
print(abs(-1234))

0.466519691
1234


 5.

In [ ]:
import random 
print(random.randint(20,91))

32


6.

In [ ]:
def retlist(list1):
  return list1[0:3]
list1=[11,12,13,14,15]
newlist=retlist(list1)
print(newlist)
np.random.shuffle(newlist)
print("After Shuffle :",newlist)
print(np.random.choice(list1))

[11, 12, 13]
After Shuffle : [12, 11, 13]
11


7. 

In [ ]:
file=open("test.txt","w")
file.write("The King is Dead, Long Live The King")
file.close()
file=open("test.txt","r")
for i in file:
  print(i,end=" ")

The King is Dead, Long Live The King 

8. 

In [ ]:
def compare(a,b):
  if a>b:
    print("A greater than B")
  elif a<b:
    print("A less than B")
  else:
    print("A equal to B")
compare(2,3)

A less than B


 9. 

In [ ]:
s="The King is Dead, Long Live The King"
print(s)
print(s[0])
print(s[2:5])
print(s[2:])
print(s.split())

The King is Dead, Long Live The King
T
e K
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


10. 

In [ ]:
a10=[1,4,5,8]
print(a10[:2])

### 11. Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 12. Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).

o Slice and display the 2nd row.

o Write code to display as array([2., 5.])

o Find the length of the array.

In [ ]:
print(arr[1])
print(arr[0][1],arr[1][1])
print(len(arr))

### 13. Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array

In [ ]:
ar=np.array([1,2,3,4,5,6,7,8,9,0])
print(ar)
ar=ar.reshape(2,5)
print(ar)

### 14. Create an array from a list of 1,2 and 3.

### 15. Fill an array [1,2,3] with a single value [9,9,9].

In [ ]:
a15=[1,2,3]
a15=np.full((3),9)
print(a15)

### 16. Sum the elements of array [2,4,5].

In [ ]:
a16=[2,4,5]
print(sum(a16))

### 17. Give the products of array [77,74,75]

In [ ]:
a17=[77,74,75]
prod=1
for i in a17:
  prod*=i
print(prod)

427350


### 18. Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.

In [ ]:
from scipy import stats
a18=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean=",np.mean(a18))
print("Median=",np.median(a18))
print("Mode=",stats.mode(a18))
print("Max=",max(a18))
print("Min=",min(a18))


Mean= 12.461538461538462
Median= 2.0
Mode= ModeResult(mode=array([1]), count=array([4]))
Max= 56
Min= 1


### 19. Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it. 

In [ ]:
a19=[1, 1, 4, 5, 5, 5, 7]
a19=list(set(a19))
a19.sort()
print(a19)

[1, 4, 5, 7]


### 20. Find dot product of two arrays [1, 2, 3]and [0, 1, 1].

In [ ]:
a20=[1,2,3]
b20=[0,1,1]
print(np.dot(a20,b20))

5


### 21. Find the eigenvalues and eigenvectors of matrix A.

In [ ]:
a21=[[2,-12],[1,-5]]
x,y=np.linalg.eig(a21)
print(x,y)

[-1. -2.] [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


### 22. Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients.

In [ ]:
a22=[[11, 22, 11, 31], [25, 33, 31, 28]]
print(np.corrcoef(a22))